// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attachments.sql

package db

import (
	"context"
)

const saveAttachment = `-- name: SaveAttachment :one
INSERT INTO attachments (email_id, type, filename, path)
VALUES ($1, $2, $3, $4)
RETURNING id, email_id, type, filename, path
`

type SaveAttachmentParams struct {
	EmailID  int32
	Type     string
	Filename string
	Path     string
}

func (q *Queries) SaveAttachment(ctx context.Context, arg SaveAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, saveAttachment,
		arg.EmailID,
		arg.Type,
		arg.Filename,
		arg.Path,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.Type,
		&i.Filename,
		&i.Path,
	)
	return i, err
}
