// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Attachment struct {
	ID               int32
	EmailID          int32
	CreatedAt        time.Time
	Type             string
	OriginalFilename string
	SavedFilename    string
	Path             string
	Cid              sql.NullString
}

type Email struct {
	ID        int32
	CreatedAt time.Time
	Subject   string
	FromEmail string
	ToEmail   string
	DateSent  time.Time
	HtmlBody  string
	TextBody  string
}
