// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Attachment struct {
	ID       int32
	EmailID  int32
	Type     string
	Filename string
	Path     string
}

type Email struct {
	ID        int32
	Subject   string
	FromEmail string
	ToEmail   string
	DateSent  time.Time
	HtmlBody  string
	TextBody  string
	CreatedAt time.Time
}
